version: '3.7'

services:
  node_api: 
    build: .
    ports: 
      - "49160:3000"
    volumes:
      - /home/rodrigo/Projetos/movie-db-api:/app
    networks:
      - dev_network

  flask_api:
    build: 
      context: src/services/flask_api
      dockerfile: Dockerfile 
    ports:
      - "49161:5000"

    networks:
      - dev_network

networks:
  dev_network: